# Generated by Django 6.0.4 on 2026-04-24 02:24

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="congregation",
            name="cong_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="congregation",
            name="cong_prefix",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="congregation",
            name="cong_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="congregation",
            name="country_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="congregation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="congregation",
            name="incoming_reports",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="congregation",
            name="outgoing_speakers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterModelTable(
            name="congregation",
            table="organized_congregation",
        ),
        migrations.CreateModel(
            name="CongUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstname", models.CharField(default="", max_length=100)),
                ("lastname", models.CharField(default="", max_length=100)),
                (
                    "user_local_uid",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "cong_role",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "user_members_delegate",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "pocket_invitation_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("sessions", models.JSONField(blank=True, default=list)),
                ("settings_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cong_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="api.congregation",
                    ),
                ),
            ],
            options={
                "db_table": "organized_cong_user",
            },
        ),
    ]
