# Generated by Django 6.0.4 on 2026-04-24 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_congregation_cong_number_congregation_cong_prefix_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CongBackupTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=64)),
                ("data", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_tables",
                        to="api.congregation",
                    ),
                ),
            ],
            options={
                "db_table": "organized_cong_backup_table",
                "unique_together": {("congregation", "table_name")},
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("value", models.CharField(default="", max_length=64)),
                (
                    "cong_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_entries",
                        to="api.conguser",
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_entries",
                        to="api.congregation",
                    ),
                ),
            ],
            options={
                "db_table": "organized_metadata",
                "unique_together": {("congregation", "cong_user", "key")},
            },
        ),
        migrations.CreateModel(
            name="UserBackupTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=64)),
                ("data", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cong_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_tables",
                        to="api.conguser",
                    ),
                ),
            ],
            options={
                "db_table": "organized_user_backup_table",
                "unique_together": {("cong_user", "table_name")},
            },
        ),
    ]
